name: "Pull Request Build"

env:
  MODERN_SLN: 'src/CSESoftware.Core.sln'

on:
  pull_request:
    branches: [ "develop", "release", "master" ]

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Nuget Restore for Modern App
      run: dotnet restore "${{ env.MODERN_SLN }}"

    - name: Setup .NET 8.0 Pre-release SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'
        include-prerelease: True
  
    - name: Setup .NET 3.1 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Build Modern Solution
      run: dotnet publish "${{ env.MODERN_SLN }}" --configuration Release
      env:
        CI: false

    - name: Run Unit Tests on Modern Solution
      run: dotnet test "${{ env.MODERN_SLN }}" --no-build --configuration Release --verbosity normal
